# skaffold build -t latest -d ""
apiVersion: skaffold/v2beta10
kind: Config
build:
  local:
    push: false
    concurrency: 8
    useBuildkit: true
  artifacts:
    - image: geth-rrr
      context: ../gopath/src/github.com/ethereum/go-ethereum
      docker:
        dockerfile: Dockerfile-rrr
    - image: rrr-delve
      context: compose
      docker:
        dockerfile: Dockerfile-delve

