apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: rrrnet-opts
  # These options are shared across all nodes.
  literals:
  - NETWORKID=53456
  - >-
    METRICS_OPTS=
    --metrics --metrics.addr 0.0.0.0 --metrics.port 6060
    --pprof --pprof.addr 0.0.0.0 --pprof.port 9545
  # RRR_OPTS It is critical (for efficient operation) that all nodes use the
  # same rrr consensus options. Using different options is effectively
  # 'byzantine' behaviour.  In future these options will likely go in the
  # genesis doc
  - >-
    RRR_OPTS=
    --rrr.roundagreement ntp
    --rrr.nc 2 --rrr.ne 7 --rrr.q 4 --rrr.ta 2000
    --rrr.intentphase 1200 --rrr.confirmphase 1600 --rrr.roundlength 3500
  - RPC_APIS=--rpcapi rrr,admin,eth,debug,miner,net,txpool,personal,web3
  - SYNC_OPTS=--gcmode archive --syncmode full
  - PRIVATE_CONFIG=ignore
  - P2P_PORT=7200
  - WS_OPTS=--ws --wsport 8400 --wsorigins '*'
  - >-
    RPC_OPTS=
    --allow-insecure-unlock
    --http
    --http.addr 0.0.0.0
    --http.port 8300
    --http.corsdomain '*'
    --http.vhosts '*'"
  - >-
    MINER_OPTS=
    --miner.gastarget 3000000000
    --mine --miner.threads 1
  - LOG_OPTS=--vmodule consensus/*=3,miner/*=2,eth/*=2,p2p/*=3 --verbosity 2
- name: genesis
  files:
  - genesis.json
