apiVersion: v1
kind: Service
metadata:
  name: bootnode
  labels:
    app: bootnode
    app.kubernetes.io/name: bootnode
    app.kubernetes.io/part-of: rrrnet

spec:
  ports:
  - name: tcp-peer
    port: 7200
  - name: tcp-rpc
    port: 8300
  - name: tcp-wsock
    port: 8400
  clusterIP: None
  selector:
    app: bootnode
