apiVersion: v1
kind: ServiceAccount
metadata:
  name: quorum-genesis-sa
  # be explicit, because the GCP SA binding only works for the declared ns
  annotations:
    iam.gke.io/gcp-service-account: quorum-genesis-sa@fetlar-1.iam.gserviceaccount.com
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: quorum-node-sa
  annotations:
    iam.gke.io/gcp-service-account: quorum-node-sa@fetlar-1.iam.gserviceaccount.com
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: quorum-membership-sa
  annotations:
    iam.gke.io/gcp-service-account: quorum-membership-sa-1@fetlar-1.iam.gserviceaccount.com
automountServiceAccountToken: true
