# This should be edited or used as starting point for your own
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
- namespace.yaml
- clusterrole.yaml
- configmap.yaml
- prometheus.yaml
- service.yaml
- jumpbox.yaml
