version: "3.8"

# This compose file supports running a prebuild image, running via go run from
# mounted sources, and running under dlv for host debugging.
#
# The debug service exists to build the image that is used to host the go tool
# chain for go run and dlv modes. It only needs to be built if the base go lang
# version is updated or delve needs to be upgraded.
#
# An .env file which sets the following variables MUST be in place
# - RRR_SRC path to rrr's quorum fork top directory 'go-etherum'
# - RRR_NODE_ROOT path to a directory containing node[n] data directories
#   for geth
# If all the nodes are set to use 'node-default', RRR_SRC is not necessary.
# If any are set to node-gorun or node-debug, it must be set.

x-node-env-defaults:
  &node-env-defaults
  NETWORKID: "53456"
  PRIVATE_CONFIG: ignore
  RRR_OPTS: "--rrr.nc 2 --rrr.ne 7 --rrr.q 4 --rrr.ta 2000 --rrr.confirmphase 1500 --rrr.roundlength 3500"
  # DISCOVERY_OPTS: "--nodiscover"
  NAT_OPTS: "--nat=none"
  DISCOVERY_OPTS: "--netrestrict=${RRR_BOOTNODE_IP}/24 --bootnodes=enode://${RRR_BOOTNODE_PUB}@${RRR_BOOTNODE_IP}:7200"
  P2P_PORT: 7200
  RPC_OPTS: "\
   --allow-insecure-unlock \
   --rpc \
   --rpcaddr 0.0.0.0 \
   --rpcport 8300 \
   --rpccorsdomain '*' \
   --rpcvhosts '*'"
  WS_OPTS: "--ws --wsport 8400 --wsorigins '*'"
  MINER_OPTS: "\
   --miner.gastarget 3000000000 \
   --mine --minerthreads 1 --miner.etherbase ${RRR_ETHERBASE}"
  LOG_OPTS: "--vmodule consensus/*=7,miner/*=3,eth/*=2,p2p/*=2 --verbosity 3"
  # --debug adds source and line no
  # LOG_OPTS: "--debug --vmodule consensus/*=7,miner/*=5 --verbosity 3"

  # Different default ways to start geth

  LAUNCH_DIR: "/"
  RUN_GETH_CMD: geth

# env for debuging from the host via dlv
x-node-env-debug:
  &node-env-debug
  << : *node-env-defaults
  GOCACHE: /tmp/go-cache
  LAUNCH_DIR: "/go/src/quorum"
  RUN_GETH_CMD: "/dbg/dlv debug --headless --listen=:2345 --log --api-version=2 github.com/ethereum/go-ethereum/cmd/geth -- "

# env for running from host sources (rather than building the image) - faster
# turnaround for very small networks, but more than 4 or 5 nodes takes a long
# time to startup.
x-node-env-gorun:
  &node-env-gorun
  << : *node-env-defaults
  GOCACHE: /tmp/go-cache
  LAUNCH_DIR: "/go/src/quorum"
  RUN_GETH_CMD: go run github.com/ethereum/go-ethereum/cmd/geth

x-node-base:
  &node-base
  volumes:
    # Defined in the .env file
    - ${RRR_NODE_ROOT}:/nodes

  entrypoint:
    - /bin/sh
    - -cx
    - |
      NODE_DIR=$$(pwd)
      cd $${LAUNCH_DIR}
      # The RUN_GETH_CMD variable is set by the environment of each of the
      # supported x-node-{flavour}'s, the others all come from node-env-defaults
      # It is assumed that the service entry sets the working_dir to the
      # correct node directory for the --nodekey and --datadir options
      $${RUN_GETH_CMD} \
          $${RRR_OPTS} \
          --networkid $${NETWORKID} \
          $${NAT_OPTS} $${DISCOVERY_OPTS} \
          --port $${P2P_PORT} \
          --nodekey $${NODE_DIR}/key \
          --datadir $${NODE_DIR}/data \
          --gcmode archive  --syncmode full \
          --nousb \
          --rpcapi "rrr,admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum" \
          $${MINER_OPTS} \
          $${RPC_OPTS} \
          $${LOG_OPTS}

x-node-defaults:
  &node-defaults
  <<: *node-base
  environment:
    << : *node-env-defaults
  image: geth-rrr:latest
  volumes:
    # Defined in the .env file
    - ${RRR_NODE_ROOT}:/nodes
  networks:
    rrr:

x-node-debug:
  &node-debug
  <<: *node-base
  environment:
    << : *node-env-debug
  image: rrr-delve:dev
  volumes:
    - go-cache-volume:/tmp/go-cache
    - go-pkg-volume:/go/pkg
    # These variables are defined in the .env file
    - ${RRR_SRC}:/go/src
    - ${RRR_NODE_ROOT}:/nodes
  ports:
    - "2345:2345"
    - "8545:8300"
  networks:
    rrr:

x-node-gorun:
  &node-gorun
  <<: *node-base
  environment:
    << : *node-env-gorun
  image: rrr-delve:dev
  volumes:
    - go-cache-volume:/tmp/go-cache
    - go-pkg-volume:/go/pkg
    # These variables are defined in the .env file
    - ${RRR_SRC}:/go/src
    - ${RRR_NODE_ROOT}:/nodes
  # ports from node-base

networks:
  rrr:
    internal: false
    ipam:
      config:
        - subnet: ${RRR_BOOTNODE_IP}/24

services:

  # * One of the nodes can be set to << : *node-debug, to be debuged via a
  #   delve connection from the host, but the others must all be node-default or
  #   node-gorun
  # * Any can be set to << : *node-gorun, but more than 3 or 4 set that way
  #   significantly slow down startup.
  #   node-defaults assumes the image referenced by x-node-defaults has been
  #   built.
  node0:
    # << : *node-debug
    << : *node-defaults
    #environment:
    #  << : *node-env-defaults
    #  NAT_OPTS: "--nat=extip:${RRR_BOOTNODE_IP}"

    working_dir: /nodes/node0
    networks:
      rrr:
        ipv4_address: ${RRR_BOOTNODE_IP}

  node1:
    << : *node-defaults
    # << : *node-debug
    working_dir: /nodes/node1

  node2:
    << : *node-defaults
    working_dir: /nodes/node2

  node3:
    << : *node-defaults
    # << : *node-debug
    working_dir: /nodes/node3

  # The tactic of using 'go run' so that it is fast to iterate code changes
  # does not scale to much more than 5 nodes - the go linker typically gets OOM
  # killed on a mac if they are all started together. And starting 5+
  # individually is a little tiresome.
  node4:
    << : *node-defaults
    working_dir: /nodes/node4

  node5:
    << : *node-defaults
    working_dir: /nodes/node5

  node6:
    << : *node-defaults
    working_dir: /nodes/node6

  node7:
    << : *node-defaults
    # << : *node-debug
    working_dir: /nodes/node7

  node8:
    << : *node-defaults
    working_dir: /nodes/node8

  node9:
    << : *node-defaults
    working_dir: /nodes/node9

  node10:
    << : *node-defaults
    working_dir: /nodes/node10

  node11:
    << : *node-defaults
    working_dir: /nodes/node11

  node12:
    << : *node-defaults
    working_dir: /nodes/node12

  node13:
    << : *node-defaults
    working_dir: /nodes/node13

  node14:
    << : *node-defaults
    working_dir: /nodes/node14

volumes:
  go-pkg-volume:
  go-cache-volume:
