FROM golang:1.15.5-alpine as builder
RUN apk add --no-cache make gcc musl-dev linux-headers git
ADD quorum /build/quorum
ADD go-rrr /build/go-rrr
RUN find /build -type d

ENV GOBIN=/go/bin

WORKDIR /build/go-rrr/tools
RUN go install github.com/RobustRoundRobin/go-rrr/tools/cmd/rrrctl

FROM alpine:latest

RUN apk add --no-cache ca-certificates

COPY --from=builder /go/bin/rrrctl /usr/local/bin/

ENTRYPOINT ["rrrctl"]

